version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-catalog
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  catalog-service:
    image: rrajo/catalog-service:dev
    build: .
    container_name: catalog-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catalogdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
